### ISSUE TITLE
No error reporting

### ISSUE THREAD

**Issue by nikoloza** [vigour-io/turbolink#2]
Because of spare coma in package.json, I was unable to run turbolink, and also it did not throw errors to understand whats up. We can also have `--verbose` for this situations.

![image](https://cloud.githubusercontent.com/assets/962224/15532894/4a8a343a-2262-11e6-917d-b5ea0d7e5fa9.png)

**Comment by jimdebeer** [comment]
before making an issue just pull or npm i -g -- also you are not using the .turbolink file thats also wrong!

**Comment by nikoloza** [comment]
That's too old Jim, it's May 25

**Comment by vigourmachines** [comment]
ah so errors in the package?
